MINECRAFT_CLASS_COLORS_RGB = dict(
    bee=(
        255,
        215,
        0,
    ),
    chicken=(
        255,
        165,
        0,
    ),
    cow=(
        139,
        69,
        19,
    ),
    creeper=(
        0,
        255,
        0,
    ),
    enderman=(
        148,
        0,
        211,
    ),
    fox=(
        255,
        69,
        0,
    ),
    frog=(
        85,
        107,
        47,
    ),
    ghast=(
        240,
        248,
        255,
    ),
    goat=(
        245,
        245,
        220,
    ),
    llama=(
        222,
        184,
        135,
    ),
    pig=(
        255,
        182,
        193,
    ),
    sheep=(
        255,
        255,
        255,
    ),
    skeleton=(
        192,
        192,
        192,
    ),
    spider=(
        45,
        45,
        45,
    ),
    turtle=(
        34,
        139,
        34,
    ),
    wolf=(
        176,
        196,
        222,
    ),
    zombie=(
        0,
        128,
        128,
    ))
auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
data_root = 'datasets/minecraft/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        _scope_='mmdet',
        interval=1,
        max_keep_ckpts=3,
        rule='greater',
        save_best='coco/bbox_mAP',
        type='CheckpointHook'),
    logger=dict(_scope_='mmdet', interval=50, type='LoggerHook'),
    param_scheduler=dict(_scope_='mmdet', type='ParamSchedulerHook'),
    sampler_seed=dict(_scope_='mmdet', type='DistSamplerSeedHook'),
    timer=dict(_scope_='mmdet', type='IterTimerHook'),
    visualization=dict(
        _scope_='mmdet',
        draw=True,
        interval=50,
        show=False,
        type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
load_from = None
log_level = 'INFO'
log_processor = dict(
    _scope_='mmdet', by_epoch=True, type='LogProcessor', window_size=50)
metainfo = dict(
    classes=(
        'bee',
        'chicken',
        'cow',
        'creeper',
        'enderman',
        'fox',
        'frog',
        'ghast',
        'goat',
        'llama',
        'pig',
        'sheep',
        'skeleton',
        'spider',
        'turtle',
        'wolf',
        'zombie',
    ),
    palette=[
        (
            255,
            215,
            0,
        ),
        (
            255,
            165,
            0,
        ),
        (
            139,
            69,
            19,
        ),
        (
            0,
            255,
            0,
        ),
        (
            148,
            0,
            211,
        ),
        (
            255,
            69,
            0,
        ),
        (
            85,
            107,
            47,
        ),
        (
            240,
            248,
            255,
        ),
        (
            245,
            245,
            220,
        ),
        (
            222,
            184,
            135,
        ),
        (
            255,
            182,
            193,
        ),
        (
            255,
            255,
            255,
        ),
        (
            192,
            192,
            192,
        ),
        (
            45,
            45,
            45,
        ),
        (
            34,
            139,
            34,
        ),
        (
            176,
            196,
            222,
        ),
        (
            0,
            128,
            128,
        ),
    ])
model = dict(
    _scope_='mmdet',
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(
            checkpoint='open-mmlab://detectron/resnet50_caffe',
            type='Pretrained'),
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='caffe',
        type='ResNet'),
    bbox_head=dict(
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=1.0, type='IoULoss'),
        loss_centerness=dict(
            loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=True),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            type='FocalLoss',
            use_sigmoid=True),
        num_classes=17,
        stacked_convs=4,
        strides=[
            8,
            16,
            32,
            64,
            128,
        ],
        type='FCOSHead'),
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            102.9801,
            115.9465,
            122.7717,
        ],
        pad_size_divisor=32,
        std=[
            1.0,
            1.0,
            1.0,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        add_extra_convs='on_output',
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        relu_before_extra_convs=True,
        start_level=1,
        type='FPN'),
    test_cfg=dict(
        max_per_img=100,
        min_bbox_size=0,
        nms=dict(iou_threshold=0.5, type='nms'),
        nms_pre=1000,
        score_thr=0.05),
    type='FCOS')
optim_wrapper = dict(
    _scope_='mmdet',
    clip_grad=None,
    optimizer=dict(lr=0.0025, momentum=0.9, type='SGD', weight_decay=0.0001),
    paramwise_cfg=dict(bias_decay_mult=0.0, bias_lr_mult=2.0),
    type='OptimWrapper')
param_scheduler = [
    dict(T_max=50, eta_min=1e-05, type='CosineAnnealingLR'),
]
resume = True
test_cfg = dict(_scope_='mmdet', type='TestLoop')
test_dataloader = dict(
    batch_size=16,
    dataset=dict(
        _scope_='mmdet',
        ann_file='test/annotations.json',
        backend_args=None,
        data_prefix=dict(img='test/'),
        data_root='datasets/minecraft/',
        metainfo=dict(
            classes=(
                'bee',
                'chicken',
                'cow',
                'creeper',
                'enderman',
                'fox',
                'frog',
                'ghast',
                'goat',
                'llama',
                'pig',
                'sheep',
                'skeleton',
                'spider',
                'turtle',
                'wolf',
                'zombie',
            ),
            palette=[
                (
                    255,
                    215,
                    0,
                ),
                (
                    255,
                    165,
                    0,
                ),
                (
                    139,
                    69,
                    19,
                ),
                (
                    0,
                    255,
                    0,
                ),
                (
                    148,
                    0,
                    211,
                ),
                (
                    255,
                    69,
                    0,
                ),
                (
                    85,
                    107,
                    47,
                ),
                (
                    240,
                    248,
                    255,
                ),
                (
                    245,
                    245,
                    220,
                ),
                (
                    222,
                    184,
                    135,
                ),
                (
                    255,
                    182,
                    193,
                ),
                (
                    255,
                    255,
                    255,
                ),
                (
                    192,
                    192,
                    192,
                ),
                (
                    45,
                    45,
                    45,
                ),
                (
                    34,
                    139,
                    34,
                ),
                (
                    176,
                    196,
                    222,
                ),
                (
                    0,
                    128,
                    128,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(poly2mask=False, type='LoadAnnotations', with_bbox=True),
            dict(keep_ratio=True, scale=(
                512,
                512,
            ), type='Resize'),
            dict(type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet', shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    _scope_='mmdet',
    ann_file='datasets/minecraft/test/annotations.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
    ],
    outfile_prefix='src/artifacts/metrics/test',
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(poly2mask=False, type='LoadAnnotations', with_bbox=True),
    dict(keep_ratio=True, scale=(
        512,
        512,
    ), type='Resize'),
    dict(type='PackDetInputs'),
]
train_cfg = dict(
    _scope_='mmdet', max_epochs=50, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_sampler=dict(_scope_='mmdet', type='AspectRatioBatchSampler'),
    batch_size=16,
    dataset=dict(
        _scope_='mmdet',
        ann_file='train/annotations.json',
        backend_args=None,
        data_prefix=dict(img='train/'),
        data_root='datasets/minecraft/',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(
            classes=(
                'bee',
                'chicken',
                'cow',
                'creeper',
                'enderman',
                'fox',
                'frog',
                'ghast',
                'goat',
                'llama',
                'pig',
                'sheep',
                'skeleton',
                'spider',
                'turtle',
                'wolf',
                'zombie',
            ),
            palette=[
                (
                    255,
                    215,
                    0,
                ),
                (
                    255,
                    165,
                    0,
                ),
                (
                    139,
                    69,
                    19,
                ),
                (
                    0,
                    255,
                    0,
                ),
                (
                    148,
                    0,
                    211,
                ),
                (
                    255,
                    69,
                    0,
                ),
                (
                    85,
                    107,
                    47,
                ),
                (
                    240,
                    248,
                    255,
                ),
                (
                    245,
                    245,
                    220,
                ),
                (
                    222,
                    184,
                    135,
                ),
                (
                    255,
                    182,
                    193,
                ),
                (
                    255,
                    255,
                    255,
                ),
                (
                    192,
                    192,
                    192,
                ),
                (
                    45,
                    45,
                    45,
                ),
                (
                    34,
                    139,
                    34,
                ),
                (
                    176,
                    196,
                    222,
                ),
                (
                    0,
                    128,
                    128,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(poly2mask=False, type='LoadAnnotations', with_bbox=True),
            dict(
                border_val=(
                    114,
                    114,
                    114,
                ),
                max_rotate_degree=30.0,
                max_translate_ratio=0.15,
                scaling_ratio_range=(
                    1.0,
                    1.0,
                ),
                type='RandomAffine'),
            dict(
                keep_ratio=True,
                scale=[
                    (
                        640,
                        640,
                    ),
                    (
                        896,
                        896,
                    ),
                ],
                type='RandomResize'),
            dict(
                allow_negative_crop=False,
                crop_size=(
                    640,
                    640,
                ),
                type='RandomCrop'),
            dict(prob=0.5, type='RandomFlip'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet', shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(poly2mask=False, type='LoadAnnotations', with_bbox=True),
    dict(
        border_val=(
            114,
            114,
            114,
        ),
        max_rotate_degree=30.0,
        max_translate_ratio=0.15,
        scaling_ratio_range=(
            1.0,
            1.0,
        ),
        type='RandomAffine'),
    dict(
        keep_ratio=True,
        scale=[
            (
                640,
                640,
            ),
            (
                896,
                896,
            ),
        ],
        type='RandomResize'),
    dict(allow_negative_crop=False, crop_size=(
        640,
        640,
    ), type='RandomCrop'),
    dict(prob=0.5, type='RandomFlip'),
    dict(type='PackDetInputs'),
]
val_cfg = dict(_scope_='mmdet', type='ValLoop')
val_dataloader = dict(
    batch_size=8,
    dataset=dict(
        _scope_='mmdet',
        ann_file='valid/annotations.json',
        backend_args=None,
        data_prefix=dict(img='valid/'),
        data_root='datasets/minecraft/',
        metainfo=dict(
            classes=(
                'bee',
                'chicken',
                'cow',
                'creeper',
                'enderman',
                'fox',
                'frog',
                'ghast',
                'goat',
                'llama',
                'pig',
                'sheep',
                'skeleton',
                'spider',
                'turtle',
                'wolf',
                'zombie',
            ),
            palette=[
                (
                    255,
                    215,
                    0,
                ),
                (
                    255,
                    165,
                    0,
                ),
                (
                    139,
                    69,
                    19,
                ),
                (
                    0,
                    255,
                    0,
                ),
                (
                    148,
                    0,
                    211,
                ),
                (
                    255,
                    69,
                    0,
                ),
                (
                    85,
                    107,
                    47,
                ),
                (
                    240,
                    248,
                    255,
                ),
                (
                    245,
                    245,
                    220,
                ),
                (
                    222,
                    184,
                    135,
                ),
                (
                    255,
                    182,
                    193,
                ),
                (
                    255,
                    255,
                    255,
                ),
                (
                    192,
                    192,
                    192,
                ),
                (
                    45,
                    45,
                    45,
                ),
                (
                    34,
                    139,
                    34,
                ),
                (
                    176,
                    196,
                    222,
                ),
                (
                    0,
                    128,
                    128,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(poly2mask=False, type='LoadAnnotations', with_bbox=True),
            dict(keep_ratio=True, scale=(
                512,
                512,
            ), type='Resize'),
            dict(type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet', shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    _scope_='mmdet',
    ann_file='datasets/minecraft/valid/annotations.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
    ],
    outfile_prefix='src/artifacts/metrics/valid',
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    _scope_='mmdet',
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'src/artifacts/checkpoints/fcos_minecraft_50e'
